# Generated by Django 4.1.3 on 2022-11-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seller_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.BooleanField(default=False, verbose_name='Арендодатель / Продавец'),
        ),
    ]
