# Generated by Django 4.1.3 on 2022-11-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='ballance',
            field=models.IntegerField(default=0),
        ),
    ]
