# Generated by Django 4.1.3 on 2022-11-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_buyer_ballance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('s', 'Продавец'), ('b', 'Покупатель')], max_length=1),
        ),
    ]
