# Generated by Django 4.1.3 on 2022-11-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('s', 'Продавец'), ('b', 'Покупатель')], max_length=1, verbose_name='Тип аккаунта'),
        ),
    ]
