# Generated by Django 4.1.3 on 2022-11-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_seller_user_delete_buyer_delete_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('s', 'Арендодатель'), ('b', 'Арендатор')], max_length=1, verbose_name='Тип аккаунта'),
        ),
    ]
