# Generated by Django 4.1.3 on 2022-11-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_seller_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.seller')),
            ],
        ),
    ]
