# Generated by Django 4.1.3 on 2022-11-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
    ]
