# Generated by Django 4.1.3 on 2022-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
