# Generated by Django 4.1.3 on 2022-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_order_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
