# Generated by Django 4.1.3 on 2022-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_alter_order_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='img',
        ),
        migrations.AddField(
            model_name='order',
            name='img_inside',
            field=models.ImageField(null=True, upload_to='photo_inside/', verbose_name='Фото внутри'),
        ),
        migrations.AddField(
            model_name='order',
            name='img_outside',
            field=models.ImageField(null=True, upload_to='photo_outside/', verbose_name='Фото снаружи'),
        ),
    ]
