# Generated by Django 4.1.3 on 2022-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_remove_order_img_order_img_inside_order_img_outside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='img_inside',
            field=models.ImageField(upload_to='photo_inside/', verbose_name='Фото внутри'),
        ),
        migrations.AlterField(
            model_name='order',
            name='img_outside',
            field=models.ImageField(upload_to='photo_outside/', verbose_name='Фото снаружи'),
        ),
    ]
