# Generated by Django 4.1.3 on 2022-11-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_alter_order_img_inside_alter_order_img_outside'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(max_length=50, null=True, verbose_name='Адрес'),
        ),
    ]
