# Generated by Django 4.1.3 on 2022-11-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_alter_order_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена за месяц аренды'),
        ),
    ]
