# Generated by Django 4.1.3 on 2022-11-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0015_order_is_arendated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_arendated',
            field=models.BooleanField(default=False, verbose_name='Арендовано'),
        ),
    ]
