# Generated by Django 4.1.3 on 2022-11-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0021_comment_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dete_time',
            new_name='date_time',
        ),
    ]
